<template>
    <div class="report-card-container">
        <div class="card">
            <div class="card-header">
                <h2 class="text-2xl font-bold mb-4">Report Card Management</h2>




                    <TabPanel header="View Report Cards">
                        <div class="p-4">
                            <!-- Student Report Cards Viewer -->
                            <div class="mb-4">
                                <h3 class="text-lg font-semibold mb-3">Student Report Cards</h3>
                                <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                                    <div class="field">
                                        <label for="view-student-select" class="block text-sm font-medium mb-2">Select Student</label>
                                        <Dropdown
                                            id="view-student-select"
                                            v-model="viewSelectedStudent"
                                            :options="students"
                                            optionLabel="fullName"
                                            optionValue="id"
                                            placeholder="Select Student to View Report Cards"
                                            class="w-full"
                                            :loading="studentsLoading"
                                            filter
                                            filterPlaceholder="Search for a student..."
                                            filterMatchMode="contains"
                                            :filterFields="['fullName', 'firstName', 'lastName', 'gradeName']"
                                        >
                                            <template #option="slotProps">
                                                <div class="flex justify-between items-center w-full">
                                                    <div class="flex flex-col">
                                                        <span class="font-medium">{{ slotProps.option.fullName }}</span>
                                                        <small class="text-gray-500">{{ slotProps.option.gradeName }}</small>
                                                    </div>
                                                </div>
                                            </template>
                                        </Dropdown>
                                    </div>
                                    <div class="field">
                                        <label class="block text-sm font-medium mb-2">&nbsp;</label>
                                        <Button @click="loadStudentReportCards" :loading="loadingReportCards" :disabled="!viewSelectedStudent" class="w-full" severity="secondary"> Load Report Cards </Button>
                                    </div>
                                </div>

                                <!-- Report Cards DataTable -->
                                <DataTable
                                    :value="studentReportCards"
                                    :loading="loadingReportCards"
                                    stripedRows
                                    
                                    
                                    class="p-datatable-sm"
                                    :emptyMessage="viewSelectedStudent ? 'No report cards found for this student.' : 'Please select a student to view report cards.'"
                                >
                                    <Column field="id" header="ID" sortable style="width: 80px" />
                                    <Column field="academicYear" header="Academic Year" sortable style="width: 120px" />
                                    <Column field="term" header="Term" sortable style="width: 80px" />
                                    <Column field="generatedAt" header="Generated Date" sortable>
                                        <template #body="{ data }">
                                            {{ formatDate(data.generatedAt) }}
                                        </template>
                                    </Column>
                                    <Column field="generatedByName" header="Generated By" sortable />
                                    <Column header="Actions" style="width: 180px">
                                        <template #body="{ data }">
                                            
                                            <Button @click="openPdfModal(data.id, data.studentName)" size="small" class="ml-2" severity="secondary" outlined>
                                                <i class="pi pi-eye mr-1"></i>
                                                View <span v-if="data.studentName">({{ data.studentName }})</span>
                                            </Button>
                                        </template>
                                    </Column>
                                </DataTable>
                            </div>

                            <!-- Class Report Cards Viewer (NEW) -->
                            <Divider />
                            <div class="mb-4">
                                <h3 class="text-lg font-semibold mb-3">Class Report Cards</h3>
                                <div class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-4">
                                    <div class="field">
                                        <label for="class-view-grade-select" class="block text-sm font-medium mb-2">Grade/Class</label>
                                        <Dropdown
                                            id="class-view-grade-select"
                                            v-model="classViewSelectedGrade"
                                            :options="grades"
                                            optionLabel="fullName"
                                            optionValue="id"
                                            placeholder="Select Grade"
                                            class="w-full"
                                            :loading="gradesLoading"
                                            filter
                                            filterPlaceholder="Search grades..."
                                        />
                                    </div>
                                    <div class="field">
                                        <label for="class-view-academic-year" class="block text-sm font-medium mb-2">Academic Year</label>
                                        <Dropdown
                                            id="class-view-academic-year"
                                            v-model="classViewAcademicYear"
                                            :options="academicYears"
                                            optionLabel="name"
                                            optionValue="id"
                                            placeholder="Select Academic Year"
                                            class="w-full"
                                            :loading="academicYearsLoading"
                                        />
                                    </div>
                                    <div class="field">
                                        <label for="class-view-term" class="block text-sm font-medium mb-2">Term</label>
                                        <Dropdown id="class-view-term" v-model="classViewSelectedTerm" :options="terms" optionLabel="label" optionValue="value" placeholder="Select Term" class="w-full" />
                                    </div>
                                    
                                    <div class="field">
                                        <div class="mt-7"></div>
                                        <Button 
                                            @click="generateClassReportCards" 
                                            :disabled="!classViewSelectedGrade || !classViewAcademicYear || !classViewSelectedTerm"
                                        >
                                            Generate Cards
                                        </Button>
                                    </div>

                                    <div class="field">
                                        <Button @click="loadClassViewReportCards" :loading="loadingClassViewBlobsTab" :disabled="!classViewSelectedGrade || !classViewAcademicYear || !classViewSelectedTerm" class="w-full mt-7" severity="secondary">
                                            Load All Class Report Cards
                                        </Button>
                                    </div>
                                    
                                </div>
                                <div v-if="loadingClassViewBlobsTab">
                                    <ProgressBar mode="indeterminate" style="height: 1px" />
                                    <div class="text-center mt-2">Loading class report cards...</div>
                                </div>
                                <div v-if="classViewReportCards.length > 0">
                                    <DataTable :value="classViewReportCards"  stripedRows class="p-datatable-sm">
                                        <Column field="studentName" header="Student" />
                                        <Column field="gradeName" header="Grade" />
                                        <Column header="Actions" style="width: 180px">
                                            <template #body="{ data }">
                                                <Button @click="openPdfModal(data.id, data.studentName)" size="small" severity="secondary" outlined>
                                                    <i class="pi pi-eye mr-1"></i>
                                                    View
                                                </Button>
                                            </template>
                                        </Column>
                                    </DataTable>
                                    <div v-if="classViewReportCards.length > 0" class="text-right text-sm text-gray-600 mt-2">
                                        Total: {{ classViewReportCards.length }} students report cards.
                                    </div>
                                    <!-- Download ZIP Button for Class Report Cards -->
                                    <div v-if="classViewReportCards.length > 0" class="mt-4 flex justify-end">
                                        <Button
                                            @click="downloadClassReportCardsZip"
                                            :loading="downloadingClassBundle"
                                            :disabled="downloadingClassBundle"
                                            severity="info"
                                            icon="pi pi-download"
                                            class="w-full"
                                        >
                                            Download All as ZIP
                                        </Button>
                                    </div>
                                    <ProgressBar v-if="isZipDownloaded"  mode="indeterminate" class="mt-0.5" style="height: 2px"></ProgressBar>
                                </div>
                                <div v-else-if="!loadingClassViewBlobsTab">
                                    <span>No class report cards loaded yet.</span>
                                </div>
                            </div>
                        </div>
                    </TabPanel>



                



                
            </div>
        </div>

        <!-- Recent Report Cards -->
      

       <!-- Class Report Card View Section -->

        

    
    

        <!-- PDF Modal -->
        <Dialog v-model:visible="showPdfModal" modal header="Report Card PDF" :style="{ width: '80vw' }" @hide="closePdfModal">
            <iframe v-if="pdfUrl" :src="pdfUrl" width="100%" height="600px" style="border: none"></iframe>
           <!-- <Button v-if="lastPdfBlob" @click="downloadDebugPdf" class="mt-2" severity="info">Download PDF (Debug)</Button> -->
        </Dialog>

        <!-- Toast for notifications -->
        <Toast />
    </div>
</template>

<script setup>
import { examService, gradeService, reportService, studentService } from '@/service/api.service';
import { useToast } from 'primevue/usetoast';
import { onMounted, onUnmounted, ref, watch } from 'vue';


// PrimeVue Components
import Button from 'primevue/button';
import Column from 'primevue/column';
import DataTable from 'primevue/datatable';
import Dialog from 'primevue/dialog';
import Divider from 'primevue/divider';
import Dropdown from 'primevue/dropdown';
import ProgressBar from 'primevue/progressbar';
import TabPanel from 'primevue/tabpanel';
import Toast from 'primevue/toast';

const toast = useToast();

// Reactive data
const activeTab = ref(0);
const students = ref([]);
const grades = ref([]);
const academicYears = ref([]);
const activeAcademicYear = ref(null);
const terms = ref([
    { label: 'Term 1', value: 1 },
    { label: 'Term 2', value: 2 },
    { label: 'Term 3', value: 3 }
]);

// Single student generation
const selectedStudent = ref(null);
const academicYear = ref(null);
const selectedTerm = ref(null);
const generating = ref(false);

// Class generation
const selectedGrade = ref(null);
const classAcademicYear = ref(null);
const selectedClassTerm = ref(null);
const generatingClass = ref(false);

// Report cards viewing
const viewSelectedStudent = ref(null);
const studentReportCards = ref([]);
const loadingReportCards = ref(false);

// Recent report cards
const recentReportCards = ref([]);

// Loading states
const studentsLoading = ref(false);
const gradesLoading = ref(false);
const academicYearsLoading = ref(false);
const downloading = ref(null);
const isZipDownloaded = ref(false);

const downloadingClassBundle = ref(false);


// Add these refs for job-based PDF generation
const mergeJobId = ref(null);
const mergeJobStatus = ref(null);
const pollingInterval = ref(null);
const canDownloadMergedPdf = ref(false);
const downloadingMergedPdf = ref(false);

// Add modal/iframe state
const showPdfModal = ref(false);
const pdfUrl = ref('');

// For class view IDs (on-demand viewing)
const classReportCardViewBlobs = ref([]); // [{ id, studentName, gradeName }]
const loadingClassViewBlobs = ref(false);


const loadClassReportCardIds = async () => {
    if (!selectedGrade.value || !classAcademicYear.value || !selectedClassTerm.value) return;
    loadingClassViewBlobs.value = true;
    classReportCardViewBlobs.value = [];
    try {
        const ids = await reportService.getClassReportCardIds(selectedGrade.value, classAcademicYear.value, selectedClassTerm.value);
        classReportCardViewBlobs.value = ids;
        console.log('classReportCardViewBlobs:', classReportCardViewBlobs.value);
    } catch (error) {
        console.error('Failed to load report card IDs:', error);
        toast.add({
            severity: 'error',
            summary: 'Error',
            detail: error.message || 'Failed to load class report card IDs',
            life: 5000
        });
        classReportCardViewBlobs.value = [];
    } finally {
        loadingClassViewBlobs.value = false;
    }
};

// Watch for changes and auto-load class report card IDs
watch([selectedGrade, classAcademicYear, selectedClassTerm], ([grade, year, term]) => {
    if (grade && year && term) {
        loadClassReportCardIds();
    } else {
        classReportCardViewBlobs.value = [];
    }
});






// For PDF debug: store the last blob for download
const lastPdfBlob = ref(null);

async function openPdfModal(reportCardId) {
    try {
        // Use the new fetchReportCardBlob method
        const blob = await reportService.fetchReportCardBlob(reportCardId);
        lastPdfBlob.value = blob; // Save for debug download
        const url = window.URL.createObjectURL(blob);
        pdfUrl.value = url;
        showPdfModal.value = true;
    } catch (error) {
        toast.add({
            severity: 'error',
            summary: 'Error',
            detail: error.message || 'Failed to load PDF',
            life: 5000
        });
    }
}

function closePdfModal() {
    showPdfModal.value = false;
    if (pdfUrl.value) {
        window.URL.revokeObjectURL(pdfUrl.value);
        pdfUrl.value = '';
    }
}


// Clean up on component unmount
onUnmounted(() => {
    if (pollingInterval.value) {
        clearInterval(pollingInterval.value);
    }
});


const downloadClassReportCardsZip = async () => {
    if (!classViewSelectedGrade.value || !classViewAcademicYear.value || !classViewSelectedTerm.value) return;
    downloadingClassBundle.value = true;
    isZipDownloaded.value = true;
    try {
        // Ensure academicYear is the year string/number, not the ID
        let academicYearValue = classViewAcademicYear.value;
        // If your academicYears list is objects with {id, name}, convert to year string
        if (typeof academicYearValue === 'object' && academicYearValue.name) {
            academicYearValue = academicYearValue.name;
        }
        // If it's an ID, find the year string
        if (typeof academicYearValue === 'number') {
            const yearObj = academicYears.value.find(y => y.id === academicYearValue);
            academicYearValue = yearObj ? yearObj.name : academicYearValue;
        }

        const response = await reportService.downloadClassReportCardsZip(
            classViewSelectedGrade.value,
            academicYearValue,
            classViewSelectedTerm.value
        );
        // Download the ZIP
        let className = 'Class';
        const gradeObj = grades.value.find(g => g.id === classViewSelectedGrade.value);
        if (gradeObj && gradeObj.fullName) {
            className = gradeObj.fullName.replace(/[^a-z0-9]/gi, '_');
        }
        const zipFileName = `${className}_Report_Cards.zip`;
        const url = window.URL.createObjectURL(response);
        const link = document.createElement('a');
        link.href = url;
        link.download = zipFileName;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        window.URL.revokeObjectURL(url);
        isZipDownloaded.value = false;
        toast.add({
            severity: 'success',
            summary: 'Success',
            detail: 'All class report cards downloaded as ZIP!',
            life: 3000
        });
    } catch (error) {
        // Handle 404 and other errors
        if (error.response && error.response.status === 404) {
            toast.add({
                severity: 'warn',
                summary: 'No Reports',
                detail: 'No report cards found for this class, year, and term.',
                life: 5000
            });
        } else {
            toast.add({
                severity: 'error',
                summary: 'Error',
                detail: error.message || 'Failed to download class report cards ZIP',
                life: 5000
            });
        }
    } finally {
        downloadingClassBundle.value = false;
    }
};





const generateClassReportCards = async () => {
    if (!classViewSelectedGrade.value || !classViewAcademicYear.value || !classViewSelectedTerm.value) {
        toast.add({
            severity: 'warn',
            summary: 'Missing Selection',
            detail: 'Please select a grade, academic year, and term before generating report cards.',
            life: 4000
        });
        generatingClass.value = false;
        return;
    }
    generatingClass.value = true;
    try {
        // Find the year name from the ID
        const yearObj = academicYears.value.find(y => y.id === classViewAcademicYear.value);
        const yearName = yearObj ? yearObj.name : classViewAcademicYear.value;
        const response = await reportService.generateClassReportCards(
            classViewSelectedGrade.value,
            yearName, // pass the year string
            classViewSelectedTerm.value
        );
        // Add student names to each report card before adding to recent list
        const reportCardsWithStudentInfo = response.map((report) => {
            const studentInfo = students.value.find((s) => s.id === report.studentId);
            return {
                ...report,
                studentName: studentInfo?.fullName || 'Unknown Student',
                gradeName: studentInfo?.gradeName || 'Unknown Grade'
            };
        });
        recentReportCards.value.unshift(...reportCardsWithStudentInfo);
        toast.add({
            severity: 'success',
            summary: 'Success',
            detail: `Generated ${response.length} report cards successfully`,
            life: 3000
        });
        // No Reset form
        //selectedGrade.value = null
        //selectedClassTerm.value = null
    } catch (error) {
        toast.add({
            severity: 'error',
            summary: 'Error',
            detail: error.message || 'Failed to generate class report cards',
            life: 5000
        });
    } finally {
        generatingClass.value = false;
    }
};

const loadStudentReportCards = async () => {
    if (!viewSelectedStudent.value) return;

    loadingReportCards.value = true;
    try {
        const response = await reportService.getStudentReportCards(viewSelectedStudent.value);
        studentReportCards.value = response;
    } catch (error) {
        toast.add({
            severity: 'error',
            summary: 'Error',
            detail: error.message || 'Failed to load report cards',
            life: 5000
        });
        studentReportCards.value = [];
    } finally {
        loadingReportCards.value = false;
    }
};


// Load initial data
const loadStudents = async () => {
    studentsLoading.value = true;
    try {
        const response = await studentService.getAll();
        // Filter to only active students and sort by name
        students.value = response
            .filter((student) => student.isActive !== false) // Include students where isActive is true or undefined
            .sort((a, b) => a.fullName.localeCompare(b.fullName))
            .map((student) => ({
                id: student.id,
                fullName: student.fullName,
                firstName: student.firstName,
                lastName: student.lastName,
                gradeId: student.gradeId,
                gradeName: student.gradeName
            }));
    } catch (error) {
        console.error('Failed to load students:', error);
        toast.add({
            severity: 'error',
            summary: 'Error',
            detail: 'Failed to load students. Please try again.',
            life: 5000
        });
        students.value = [];
    } finally {
        studentsLoading.value = false;
    }
};

const loadGrades = async () => {
    gradesLoading.value = true;
    try {
        // Using grade service instead of direct API call
        const response = await gradeService.getAll();

        // Filter active grades and sort by level for better UX
        grades.value = response
            .filter((grade) => grade.isActive)
            .sort((a, b) => a.level - b.level)
            .map((grade) => ({
                id: grade.id,
                fullName: grade.fullName,
                name: grade.name,
                stream: grade.stream,
                section: grade.section,
                level: grade.level,
                studentCount: grade.studentCount,
                homeroomTeacherName: grade.homeroomTeacherName
            }));
    } catch (error) {
        console.error('Failed to load grades:', error);
        toast.add({
            severity: 'error',
            summary: 'Error',
            detail: 'Failed to load grades. Please try again.',
            life: 5000
        });
        grades.value = [];
    } finally {
        gradesLoading.value = false;
    }
};

const loadAcademicYears = async () => {
    academicYearsLoading.value = true;
    try {
        // Load all academic years and active academic year
        const [allYears, activeYear] = await Promise.all([examService.getAcademicYears(), examService.getActiveAcademicYear()]);

        console.log('🔍 Academic Years Response:', allYears);
        console.log('🔍 Active Year Response:', activeYear);

        // Handle the response structure - it might be direct array or wrapped
        const yearsArray = Array.isArray(allYears) ? allYears : allYears.data || [];

        // Sort academic years by year descending (most recent first)
        academicYears.value = yearsArray
            .sort((a, b) => {
                const yearA = parseInt(a.name) || 0;
                const yearB = parseInt(b.name) || 0;
                return yearB - yearA;
            })
            .map((year) => ({
                id: year.id,
                name: year.name,
                year: parseInt(year.name), // Convert name to number for easier handling
                startDate: year.startDate,
                endDate: year.endDate,
                isActive: year.isActive,
                isClosed: year.isClosed
            }));

        console.log('🔍 Processed Academic Years:', academicYears.value);

        // Set active academic year as default
        if (activeYear) {
            activeAcademicYear.value = activeYear;
            const activeYearValue = parseInt(activeYear.name);
            academicYear.value = activeYearValue;
            classAcademicYear.value = activeYearValue;
            console.log('🔍 Set Active Year:', activeYearValue);
        }
    } catch (error) {
        console.error('Failed to load academic years:', error);
        toast.add({
            severity: 'error',
            summary: 'Error',
            detail: 'Failed to load academic years. Please try again.',
            life: 5000
        });
        academicYears.value = [];
    } finally {
        academicYearsLoading.value = false;
    }
};

// Utility functions
const formatDate = (dateString) => {
    if (!dateString) return '';
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
    });
};

const getSelectedGradeInfo = (gradeId) => {
    const grade = grades.value.find((g) => g.id === gradeId);
    return grade ? `${grade.fullName} (${grade.studentCount} students)` : '';
};

const getSelectedAcademicYearInfo = (yearValue) => {
    const year = academicYears.value.find((y) => y.year === yearValue);
    return year ? year.name : yearValue;
};

// Lifecycle
onMounted(() => {
    loadAcademicYears();
    loadStudents();
    loadGrades();
});

// Add new refs and method in <script setup>:
const classViewSelectedGrade = ref(null);
const classViewAcademicYear = ref(null);
const classViewSelectedTerm = ref(null);
const classViewReportCards = ref([]);
const loadingClassViewBlobsTab = ref(false);

const loadClassViewReportCards = async () => {
    if (!classViewSelectedGrade.value || !classViewAcademicYear.value || !classViewSelectedTerm.value) return;
    loadingClassViewBlobsTab.value = true;
    classViewReportCards.value = [];
    try {
        const ids = await reportService.getClassReportCardIds(classViewSelectedGrade.value, classViewAcademicYear.value, classViewSelectedTerm.value);
        classViewReportCards.value = ids;
    } catch (error) {
        toast.add({
            severity: 'error',
            summary: 'Error',
            detail: error.message || 'Failed to load class report cards',
            life: 5000
        });
        classViewReportCards.value = [];
    } finally {
        loadingClassViewBlobsTab.value = false;
    }
};
</script>

<style scoped>
.report-card-container {
    padding: 1rem;
    max-width: 1200px;
    margin: 0 auto;
}

.card {
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    padding: 1.5rem;
}

.card-header {
    border-bottom: 1px solid #e5e7eb;
    padding-bottom: 1rem;
    margin-bottom: 1rem;
}

.field {
    display: flex;
    flex-direction: column;
}

.grid {
    display: grid;
    gap: 1rem;
}

.grid-cols-1 {
    grid-template-columns: repeat(1, minmax(0, 1fr));
}

@media (min-width: 768px) {
    .md\:grid-cols-2 {
        grid-template-columns: repeat(2, minmax(0, 1fr));
    }

    .md\:grid-cols-4 {
        grid-template-columns: repeat(4, minmax(0, 1fr));
    }
}

.text-2xl {
    font-size: 1.5rem;
    line-height: 2rem;
}

.text-lg {
    font-size: 1.125rem;
    line-height: 1.75rem;
}

.text-sm {
    font-size: 0.875rem;
    line-height: 1.25rem;
}

.font-bold {
    font-weight: 700;
}

.font-semibold {
    font-weight: 600;
}

.font-medium {
    font-weight: 500;
}

.mb-2 {
    margin-bottom: 0.5rem;
}

.mb-3 {
    margin-bottom: 0.75rem;
}

.mb-4 {
    margin-bottom: 1rem;
}

.mb-6 {
    margin-bottom: 1.5rem;
}

.mt-4 {
    margin-top: 1rem;
}

.mr-1 {
    margin-right: 0.25rem;
}

.w-full {
    width: 100%;
}

.block {
    display: block;
}

.flex {
    display: flex;
}

.flex-col {
    flex-direction: column;
}

.justify-between {
    justify-content: space-between;
}

.items-center {
    align-items: center;
}

.text-gray-500 {
    color: #6b7280;
}

.text-green-600 {
    color: #059669;
}

.text-red-600 {
    color: #dc2626;
}

.gap-2 {
    gap: 0.5rem;
}
</style>
